name: GrandTheftDiamond
main: me.micrjonas.grandtheftdiamond.BukkitGrandTheftDiamondPlugin
version: Beta_1.11.8
author: MiCrJonas1997
description: The GTA plugin for Minecraft!
website: http://dev.bukkit.org/bukkit-plugins/grand-theft-diamond/
softdepend:
- BarAPI
- Citizens
- Dynmap
- NametagEdit
- Vault
commands:
  gtd: 
    description: Use '/gtd ? [page]' for the plugin's command help
    aliases:
    - gta
    - grandtheftauto
    - grandtheftdiamond
    - gtdiamond
    - gt-diamond